name: dit-cs
channels:
  - conda-forge
  - defaults
  - pytorch
  - iopath
dependencies:
  #- cudatoolkit=11.8.0
  - cudatoolkit=12.4.0
  - python=3.8.19
  - pytorch::pytorch=2.4.0
  - pytorch::torchvision=0.19.0
  - pytorch-lightning=2.4.0
  - deepspeed
  - matplotlib
  - scipy
  - h5py
  - pyyaml
  - flit
  - fvcore
  - iopath
  - moviepy
  - einops
  - timm
  - tensorboard