# Example Config file from dl-ss-recon repo

OUTPUT_DIR: "/data/sandino/TorchData/cine/summary/dslr_experiments/dslr-cg-10-10steps_2resblocks_128features"

MODEL:
  META_ARCHITECTURE: "dslr"
  PARAMETERS:
    NUM_UNROLLS: 10
    NUM_RESBLOCKS: 2
    NUM_FEATURES: 128
    NUM_EMAPS: 2
    SHARE_WEIGHTS: False
    FIX_STEP_SIZE: True
    SLWIN_INIT: True
    GRAD_CHECKPOINT: True
    DSLR:
      NUM_BASIS: 8
      BLOCK_SIZE: 16
      OVERLAPPING: True
      NUM_CG_STEPS: 10
    CONV_BLOCK:
      ACTIVATION: "relu"
      NORM: "none"
      CIRCULAR_PAD: True
      SEPARABLE: False
      COMPLEX: False
  RECON_LOSS:
    NAME: "complex_l1"
    RENORMALIZE_DATA: False

# Paths to training and validation sets
DATASET:
  TRAIN: ("/data/sandino/TorchData/cine/train",)
  VAL: ("/data/sandino/TorchData/cine/validate",)

DATALOADER:
  TRAIN_BATCH_SIZE: 1
  VAL_BATCH_SIZE: 1

# Flags for augmentation on training set
AUG_TRAIN:
  UNDERSAMPLE:
    NAME: VDktMaskFunc
    ACCELERATIONS: (10, 15)
    PARTIAL_KX: 0.25 # fraction of kx samples to exclude
    PARTIAL_KY: 0.25 # fraction of ky samples to exclude

# Flags for SGD optimizer
OPTIMIZER:
  NAME: "Adam"
  MAX_EPOCHS: 1000
  GRAD_ACCUM_ITERS: 1
  ADAM:
    LR: 0.0001

# Flags for validation
EVAL:
  RUN_EVERY_N_EPOCHS: 1

# Logger options
LOGGER:
  LOG_METRICS_EVERY_N_STEPS: 50
  LOG_IMAGES_EVERY_N_STEPS: 50

# Misc options
SEED: 1000
VERSION: 1