# Example Config file from dl-ss-recon repo
MODEL:
  MODEL_TYPE: "SWIN"   #"RES" for resnet or "SE" for squeeze excitation
  META_ARCHITECTURE: "dlespirit"
  STRATEGY: "standard"   #deepspeed vs standard
  PARAMETERS:
    NUM_UNROLLS: 5
    NUM_RESBLOCKS: 2
    NUM_SWINBLOCKS: 1
    NUM_FEATURES: 160   #this is to match swin_t embed dims
    NUM_EMAPS: 2
    SHARE_WEIGHTS: False
    FIX_STEP_SIZE: True
    SLWIN_INIT: True
    GRAD_CHECKPOINT: False
    CONV_BLOCK:
      ACTIVATION: "relu"
      NORM: "none"
      CIRCULAR_PAD: True
      COMPLEX: False
  RECON_LOSS:
    NAME: "complex_l1"
    #NAME: "complex_vggloss"
    RENORMALIZE_DATA: False
    LOSS_WEIGHT: False

# Paths to training and validation sets
DATASET:
  #TRAIN: ("/mnt/dense/sandino/TorchData/stanfordCine/train",)
  #VAL: ("/mnt/dense/sandino/TorchData/stanfordCine/validate",)
  # 1 EMAP
  # TRAIN: ("/home/tjao/data/stanfordCine/train",)
  # VAL: ("/home/tjao/data/stanfordCine/validate",)
  # 2 EMAP
  TRAIN: ("/home/tjao/data/stanfordCine_2emaps/train",)
  VAL: ("/home/tjao/data/stanfordCine_2emaps/validate",)
DATALOADER:
  TRAIN_BATCH_SIZE: 1
  VAL_BATCH_SIZE: 1

# Flags for augmentation on training set
AUG_TRAIN:
  #CROP_READOUT: 64 # number of readout points to keep
  CROP_READOUT: 64
  UNDERSAMPLE:
    NAME: VDktMaskFunc
    ACCELERATIONS: (10, 15)
    PARTIAL_KX: 0.25 # fraction of kx samples to exclude
    PARTIAL_KY: 0.25 # fraction of ky samples to exclude

# Flags for SGD optimizer
OPTIMIZER:
  NAME: "Adam"
  MAX_EPOCHS: 999
  GRAD_ACCUM_ITERS: 1
  ADAM:
    LR: 0.0001

# Flags for validation
EVAL:
  RUN_EVERY_N_EPOCHS: 1

# Logger options
LOGGER:
  LOG_METRICS_EVERY_N_STEPS: 50
  LOG_IMAGES_EVERY_N_STEPS: 50

# Misc options
SEED: 1000
# OUTPUT_DIR: "/mnt/dense/sandino/TorchData/stanfordCine/summary/example/train-3D_5steps_2resblocks_64features"
#OUTPUT_DIR: "/home/tjao/data/stanfordCine_2emaps/summary/example/train-3D_5steps_2SEblocks_64features_2emaps_1weight"
#OUTPUT_DIR: "/home/tjao/data/stanfordCine_2emaps/summary/example/train-3D_5steps_2SWINblocks_84features_2emaps_0weight_6SWIN_slide"
#OUTPUT_DIR: "/home/tjao/data/stanfordCine_2emaps/summary/train-3D_5steps_2SWINblocks_80features_2emaps_0weight_6SWIN_788WIN"
OUTPUT_DIR: "/home/tjao/data/stanfordCine_2emaps/summary/train-3D_5steps_1SWINblocks_160features_2emaps_0weight_6SWIN_788WIN_test"
VERSION: 1
